# this file is to describe the data type, training column and target column names.
# This is to check if all the training columns and target columns are present inside the training data  

COLUMNS:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64
  chlorides: float64
  free sulfur dioxide: float64
  total sulfur dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  quality: int64


TARGET_COLUMN:
  name: quality
  